param(
    [string] $PlanPath = "test/ui-test-plan.md",
    [string] $SessionPath = "test/ui-test-session.md"
)

$ErrorActionPreference = "Stop"

function Get-FencedBlock {
    param(
        [string] $Section,
        [string] $Label
    )

    $pattern = [regex]::Escape($Label) + ':\s*```text\s*(.*?)\s*```'
    $match = [regex]::Match($Section, $pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
    if (-not $match.Success) {
        throw "Could not find '$Label' block in a test case."
    }

    return $match.Groups[1].Value.Trim()
}

function Assert-FragmentsInOrder {
    param(
        [string] $Actual,
        [string[]] $ExpectedLines,
        [string] $CaseName
    )

    $searchStart = 0
    foreach ($line in $ExpectedLines) {
        $expected = $line.TrimEnd()
        if ($expected.Length -eq 0) {
            continue
        }

        $nextIndex = $Actual.IndexOf($expected, $searchStart, [System.StringComparison]::Ordinal)
        if ($nextIndex -lt 0) {
            Write-Host "FAILED: $CaseName"
            Write-Host "Missing or out-of-order expected output:"
            Write-Host $expected
            Write-Host ""
            Write-Host "Actual output:"
            Write-Host $Actual
            exit 1
        }

        $searchStart = $nextIndex + $expected.Length
    }
}

$sources = Get-ChildItem -Path "src/main/java" -Filter "*.java" | ForEach-Object { $_.FullName }
& javac -d bin $sources
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

$plan = Get-Content -LiteralPath $PlanPath -Raw
$caseMatches = [regex]::Matches($plan, "(?ms)^## Test Case \d+: .+?(?=^## Test Case \d+: |\z)")
if ($caseMatches.Count -eq 0) {
    throw "No test cases found in $PlanPath."
}

$session = New-Object System.Collections.Generic.List[string]
$session.Add("# UI Test Session")
$session.Add("")
$session.Add("Generated by test/run-ui-tests.ps1.")

foreach ($caseMatch in $caseMatches) {
    $section = $caseMatch.Value
    $title = ([regex]::Match($section, "^## (.+)$", [System.Text.RegularExpressions.RegexOptions]::Multiline)).Groups[1].Value
    $commands = Get-FencedBlock -Section $section -Label "Commands"
    $expected = Get-FencedBlock -Section $section -Label "Expected output fragments"

    $inputText = $commands.TrimEnd() + "`n"
    $actual = $inputText | & java -cp bin Yappy
    $actualText = ($actual -join "`n")

    $expectedLines = $expected -split "`r?`n"
    Assert-FragmentsInOrder -Actual $actualText -ExpectedLines $expectedLines -CaseName $title

    $session.Add("")
    $session.Add("## $title")
    $session.Add("")
    $session.Add("Console input:")
    $session.Add('```text')
    $session.Add($commands)
    $session.Add('```')
    $session.Add("")
    $session.Add("Console output:")
    $session.Add('```text')
    $session.Add($actualText)
    $session.Add('```')
}

Set-Content -LiteralPath $SessionPath -Value $session
Write-Host "All UI test cases passed. Session written to $SessionPath."
